language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install -r requirements/local.txt

script:
  - export SECRET_KEY=super.secret.key
  - export DJANGO_SETTINGS_MODULE=etorta.settings.test
  - cd etorta
  - python manage.py test
